add missing dependency "deepdiff" because of the following error ...
Traceback (most recent call last):
  File "/home/mymn/Dokumente/Ulanzi-D200-Linux/ulanzi-d200-linux/venv/bin/ulanzi-manager", line 3, in <module>
    from ulanzi_manager.cli import main
  File "/home/mymn/Dokumente/Ulanzi-D200-Linux/ulanzi-d200-linux/ulanzi_manager/cli.py", line 9, in <module>
    from ulanzi_manager.device import UlanziDevice
  File "/home/mymn/Dokumente/Ulanzi-D200-Linux/ulanzi-d200-linux/ulanzi_manager/device.py", line 12, in <module>
    from deepdiff import DeepDiff
ModuleNotFoundError: No module named 'deepdiff'